# Generated by Django 6.0.7 on 2026-08-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Health Post', 'Health Post'), ('Pharmacy', 'Pharmacy')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('specializations_raw', models.TextField(help_text='Comma-separated specializations or doctor services')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Emergency Only', 'Emergency Only')], default='Available', max_length=50)),
            ],
        ),
    ]
