# Generated by Django 6.1 on 2026-08-21 09:50

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcarefacility',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='healthcarefacility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthcarefacility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='latitude',
            field=models.FloatField(help_text='Latitude between -90 and 90.', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='longitude',
            field=models.FloatField(help_text='Longitude between -180 and 180.', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='specializations_raw',
            field=models.TextField(blank=True, default='', help_text='Comma-separated specializations or doctor services.'),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Emergency Only', 'Emergency Only')], db_index=True, default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='type',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Health Post', 'Health Post'), ('Pharmacy', 'Pharmacy')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcarefacility',
            name='website',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='healthcarefacility',
            index=models.Index(fields=['type'], name='facility_type_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcarefacility',
            index=models.Index(fields=['status'], name='facility_status_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcarefacility',
            index=models.Index(fields=['name'], name='facility_name_idx'),
        ),
    ]
